textkernel/oneui

src/components/Alert/Alert.js

* This will add support for defining context for Alert actions (currently it would always be 'link')

Support button contexts for alert action

---

.eslintrc.json
.storybook/webpack.config.js
src/index.js
stories/Alert.js
stories/Button.js
stories/ButtonGroup.js
stories/CandidateAvatar.js
stories/Checkbox.js
stories/Heading.js
stories/Input.js
stories/Link.js
stories/LoadingSpinner.js
stories/ProgressBar.js
stories/RadioButton.js
stories/Tabs.js
stories/Text.js
stories/TextArea.js

Added alias for `@textkernel/oneui` in Storybook webpack config, so we can use it as a module in our stories. This is also useful to ensure that components are properly exported (already fixed two of them).

Add alias for @textkernel/oneui in Storybook webpack config

---

src/components/CandidateAvatar/CandidateAvatar.js
src/components/CandidateAvatar/CandidateAvatar.scss
src/components/CandidateAvatar/__tests__/CandidateAvatar.spec.js
src/components/CandidateAvatar/__tests__/__snapshots__/CandidateAvatar.spec.js.snap

* Switched to use SVG text to make percentage scale to fit parent container, no matter what size.

Make CandidateAvatar percentage scale to fit

---

stories/Tabs.js

* Updates `Tabs` story for controlled tabs to prevent default on tab click, it would otherwise follow the tab href

Tabs story improvements

---

stories/.eslintrc.json
stories/Alert.js
stories/Button.js
stories/ButtonGroup.js
stories/CandidateAvatar.js
stories/Checkbox.js
stories/Footer.js
stories/Header.js
stories/Heading.js
stories/Icon.js
stories/Input.js
stories/Link.js
stories/LoadingSpinner.js
stories/Navigation.js
stories/ProgressBar.js
stories/RadioButton.js
stories/Tabs.js
stories/Text.js
stories/TextArea.js

* Adds and disables `import/no-extraneous-dependencies` in `stories/.eslintrc.json` so we don't have to repeat it all over our stories

Storybook: ignore import/no-extraneous-dependencies

---

.travis.yml

Specify exact Node version in .travis.yml to prevent build from failing
Ref: https://github.com/facebook/jest/issues/8069

Specify exact Node version to fix build

---

src/components/LoadingSpinner/LoadingSpinner.js
src/components/LoadingSpinner/__tests__/LoadingSpinner.spec.js
src/components/ProgressBar/ProgressBar.js
src/components/ProgressBar/__tests__/ProgressBar.spec.js
stories/LoadingSpinner.js
stories/ProgressBar.js

* Change `LoadingSpinner` and `ProgressBar` to take their user-defined label from `children` prop instead of `label` (to be removed)

LoadingSpinner and ProgressBar: Use children instead of label prop

---

etc/webpack/webpack.prod.config.js
package-lock.json
package.json

It seems `uglifyjs-webpack-plugin` is causing builds that use the React Hooks API to break:
* https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/374
* https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/393
* https://github.com/facebook/react/issues/14014
Also, it's said that the package is not actively maintained and can best be replaced with `terser-webpack-plugin`. Webpack docs [mention Terser too](https://webpack.js.org/guides/production/#minification).
* Replaces devDependency `uglifyjs-webpack-plugin` with `terser-webpack-plugin`, preserving same configuration.

Replace uglifyjs-webpack-plugin with terser-webpack-plugin

---

src/components/ContentPlaceholder/ContentPlaceholder.js
src/components/ContentPlaceholder/ContentPlaceholder.scss
src/components/ContentPlaceholder/__tests__/ContentPlaceholder.spec.js
src/components/ContentPlaceholder/__tests__/__snapshots__/ContentPlaceholder.spec.js.snap
src/components/ContentPlaceholder/index.js
src/index.js
stories/ContentPlaceholder.js
stories/index.js

Adds a simple `ContentPlaceholder` component
* `height`: Variable placeholder height in pixels. When not set, it will inherit `lineHeight` by default.
* `width`: Variable placeholder width, relative to the parent container. When not set, it will default to `100%`.
* `duration`: Custom animation duration in seconds. When not set, it will default to `1s`.
The component is to be used inside a block-level parent element (or an element that has a width defined).

Content placeholder

---

src/components/Alert/__tests__/__snapshots__/Alert.spec.js.snap
src/components/Button/Button.js
src/components/Button/__tests__/__snapshots__/Button.spec.js.snap
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap

The `context` prop was not part of the destructuring assignment, causing it to be applied as an HTML attribute to the rendered `button` element.

fix(button): do not apply context as element attribute

---

stories/LoadingSpinner.js

Reinstate all LoadingSpinner storybook knobs that went missing (other than `centerIn`)

fix(storybook): reinstate missing knobs for loadingspinner

---

src/components/Button/Button.js
src/components/Checkbox/Checkbox.js
src/components/Input/Input.js
src/components/RadioButton/RadioButton.js
src/components/TextArea/TextArea.js

* Forwards `ref` for `Button`, `Input`, `TextArea`, `RadioButton` and `Checkbox` components to allow accessing rendered DOM element (e.g. to programmatically set focus, determine position / dimensions on screen)
BREAKING CHANGE: Ref forwarding may introduce observably different behavior

feat: forward refs in form components

---

src/components/Button/Button.js
src/components/ButtonGroup/ButtonGroup.js
src/components/CandidateAvatar/CandidateAvatar.js
src/components/Input/Input.js
src/components/ProgressBar/ProgressBar.js

Some components still use relative paths for importing the bem package, which is not necessary. Updated those components.

chore: dont use relative paths for importing bem package

---

src/components/Button/Button.scss

Fix issue with buttons that use `<a />` tags which in Safari have a different height from regular buttons

fix(button): fix height issues with anchor-buttons in safari

---

.storybook/config.js

Run `OneUI.init` before loading stories, so css-vars-ponyfill is loaded and styles work in IE11 too

fix(storybook): initialize oneui before loading stories

---

src/components/Link/Link.scss

Don't set font attributed directly on Link, but let the context determine size and so on.

fix: remove font specifications from Link

---

src/components/ButtonGroup/ButtonGroup.scss

Fix border-radius on the left side of ButtonGroups containing only a single button

fix: styling for buttongroup with single button

---

src/components/Footer/Footer.js
src/components/Footer/__tests__/__snapshots__/Footer.spec.js.snap
src/components/Header/__tests__/__snapshots__/Header.spec.js.snap
src/components/Icon/IconBase.js
src/components/Icon/__tests__/__snapshots__/IconBase.spec.js.snap
stories/Footer.js

Use TK logo instead of icon and text, also fixes `margin` attribute being applied to IconBase because it is not destructured from props.

fix: update default footer copyright

---

src/components/Alert/__tests__/__snapshots__/Alert.spec.js.snap
src/components/Button/Button.js
src/components/Button/__tests__/__snapshots__/Button.spec.js.snap
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap
src/components/Checkbox/Checkbox.js
src/components/Checkbox/__tests__/Checkbox.spec.js
src/components/Checkbox/__tests__/__snapshots__/Checkbox.spec.js.snap
src/components/Pagination/__tests__/__snapshots__/Pagination.spec.js.snap
src/components/RadioButton/RadioButton.js
src/components/RadioButton/__tests__/RadioButton.spec.js
src/components/RadioButton/__tests__/__snapshots__/RadioButton.spec.js.snap

* Destruct props that should not be applied as attributes in rendered html
* Remove `disabled` attribute from Checkbox / RadioButton label as [it isn't valid html](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Attributes)

fix: destruct props that should not be applied as html attributes

---

src/components/Button/Button.scss
src/components/ButtonGroup/ButtonGroup.js
src/components/ButtonGroup/ButtonGroup.scss
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap
stories/ButtonGroup.js

* Add separators in between buttons
* Define `context` on button group level, applies to all buttons in the group
* Deprecate `isInline` prop: ButtonGroup is inline element by default, can be toggled to `isBlock` through prop
BREAKING CHANGE: ButtonGroup isInline prop is deprecated

fix(buttongroup): add separators, define context on group level, remove isInline prop

---

etc/test/jest.config.js

Do not include `packages/bem/` in code coverage reporting. Tests are still executed but since it is to be split off to a separate package it's not very relevant to be included in coverage report. Codecov report gives a more relevant and accurate indication of test coverage for actual OneUI components.

chore(jest): ignore packages/bem in codecov report

---

src/components/Button/Button.scss

* Use box-sizing `border-box` so paddings are included, otherwise button (group) can overflow parent container when `isBlock` applied
* Center-align button labels (notable when `isBlock` is applied)

fix(button): include padding with box sizing; center-align button labels

---

CONTRIBUTING.md
RELEASING.md

* Add note about doing a dry run first when releasing
* Make it more clear how to indicate breaking changes in commit message
* Add type `build` to commit message format docs

docs: extend documentation about releasing and commit message format

---

src/utils/OneUI/OneUI.js
src/utils/OneUI/__tests__/OneUI.spec.js

Initial idea was to call OneUI.init() once on page load (that used to call
OneUI.startCssVarsPonyfill underthegood). But with code splitting
`cssVarsPonyfill` should be appled after any route navigation.
So it should be exposed with a more meaningfull name.
BREAKING CHANGE: if you used `OneUI.startCssVarsPonyfill()` directly in your app
rename it to `OneUI.applyCssVarsPonyfill()`.

feat: renamed OneUI.startCssVarsPonyfill to OneUI.applyCssVarsPonyfill()

---

src/components/LocationSelector/LocationSelector.js
src/components/LocationSelector/LocationSelector.scss
src/components/LocationSelector/LocationSelectorDialog/LocationSelectorDialog.js
src/components/LocationSelector/LocationSelectorDialog/LocationSelectorDialog.scss
src/components/LocationSelector/LocationSelectorDialog/__tests__/LocationSelectorDialog.spec.js
src/components/LocationSelector/LocationSelectorDialog/__tests__/__snapshots__/LocationSelectorDialog.spec.js.snap
src/components/LocationSelector/LocationSelectorDialog/index.js
src/components/LocationSelector/LocationSelectorDialogWithGoogleLoader/LocationSelectorDialogWithGoogleLoader.js
src/components/LocationSelector/LocationSelectorDialogWithGoogleLoader/__tests__/LocationSelectorDialogWithGoogleLoader.spec.js
src/components/LocationSelector/LocationSelectorDialogWithGoogleLoader/__tests__/__snapshots__/LocationSelectorDialogWithGoogleLoader.spec.js.snap
src/components/LocationSelector/LocationSelectorDialogWithGoogleLoader/index.js
src/components/LocationSelector/__tests__/LocationSelector.spec.js
src/components/LocationSelector/__tests__/__snapshots__/LocationSelector.spec.js.snap
src/components/LocationSelector/index.js
src/index.js
stories/LocationSelector.js

Story: [ONEUI-95](https://jira.textkernel.nl/browse/ONEUI-95)
BREAKING CHANGE: LocationSelector and related components has been renamed. For top level use LocationSelector (instead of LocationSelectorWithGoogleLoader which has been deprecated). For sub components see documentation.

fix(LocationSelector): rename components and fix unit tests

---

src/components/Callout/Callout.scss
src/components/Callout/Callout.tsx
src/components/Callout/__tests__/__snapshots__/Callout.spec.js.snap
stories/Callout.tsx

* `<div>` allows to render block-level HTML elements as Callout's children;
* BREAKING CHANGE: `lineHeightStyle` removed. This property was
redundant. Styling must be handled by passing a className.

 feat(Callout): changed `<p>` to `<div>` for content element, removed `lineHeightStyle`

---

src/themes/oneui/base-variables/_colors.scss

Update base OneUI colors (`brand`, `muted`) to match new Textkernel brand guidelines

chore: update base oneui theme colors

---

src/components/FieldWithValidation/FieldWithValidation.tsx
src/components/FieldWithValidation/__tests__/FieldWithValidation.spec.js
src/components/FieldWithValidation/__tests__/__snapshots__/FieldWithValidation.spec.js.snap
src/components/PopupBase/PopupBase.js
src/components/PopupBase/__tests__/PopupBase.spec.js
src/components/PopupBase/__tests__/__snapshots__/PopupBase.spec.js.snap
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/TooltipAnchor.tsx
src/components/Tooltip/__tests__/Tooltip.spec.js
src/components/Tooltip/__tests__/__snapshots__/Tooltip.spec.js.snap
src/hooks/index.ts
src/hooks/usePrevious.ts
stories/FieldWithValidation.tsx
stories/Tooltip.tsx

Story: [ONEUI-146](https://jira.textkernel.nl/browse/ONEUI-146)
Changes to behaviour:
* always render tooltip in FieldWithValidation when `useTooltip` is set to true
* always show tooltip if underlying component is focused
* allow `null` as result of renderPopup() in PopupBase
* do not render tooltip popup if it has no content
* add 'always visible' option to Tooltip

fix(FieldWithValidation): change logic when using tooltip

---

src/components/Select/AutosuggestMulti/AutosuggestMulti.tsx
src/components/Select/AutosuggestMulti/__tests__/AutosuggestMulti.spec.js
src/components/Select/AutosuggestMulti/__tests__/__snapshots__/AutosuggestMulti.spec.js.snap
src/components/Select/ComboboxMulti/ComboboxMulti.tsx
src/components/Select/ComboboxMulti/__tests__/ComboboxMulti.spec.js
src/components/Select/ComboboxMulti/__tests__/__snapshots__/ComboboxMulti.spec.js.snap
src/components/Select/SelectBase/SelectBase.tsx
src/components/Select/SelectBase/__tests__/SelectBase.spec.js
src/components/Select/SelectBase/__tests__/__snapshots__/SelectBase.spec.js.snap
src/components/Select/SelectBase/interfaces.ts
src/components/Select/SuggestionsList/SuggestionsList.tsx
stories/Select.tsx

Story: [ONEUI-199](https://jira.textkernel.nl/browse/ONEUI-199)
* add `noSuggestionsPlaceholder` support to AutosuggestMulti
* update props descriptions
BREAKING CHANGE:
* rename `onSuggestionChange` to `onSuggestionAdd` to align with already existing `onSuggestionRemove` prop. Effects AutosuggestMulti and ComboboxMulti

feat(Select): make props clearer

---

src/components/PopupBase/PopupBase.js
src/components/PopupBase/__tests__/PopupBase.spec.js

Make PopupBase work correctly in FireFox, Safari, and IE11
A Chrome specific event's property "path" was used in PopupBase component.
It was replaced with Event#composedPath(), that is supported by FF and Safari.

fix(PopupBase): made PopupBase#wasPopupClicked() work in FF

---

src/index.ts
src/packages/BooleanQueryTokenizer/BooleanQueryTokenizer.ts
src/packages/BooleanQueryTokenizer/__tests__/BooleanQueryTokenizer.spec.js
src/packages/BooleanQueryTokenizer/index.ts
stories/index.ts
stories/packages/BooleanQueryTokenizer.tsx

Move BooleanQueryTokenizer from reach-ui project to OneUI library.
BooleanQueryTokenizer allows to tokenize boolean query language.
Also it provides a method `extractWordsAndPhrases` that returns bag of phrases and words.

feat: implemented BooleanQueryTokenizer package

---

src/components/Teaser/Teaser.scss
src/components/Teaser/Teaser.tsx
src/components/Teaser/__tests__/Teaser.spec.js
src/components/Teaser/__tests__/__snapshots__/Teaser.spec.js.snap
stories/Teaser.tsx

- add statuses array
- add fixed height
- implement 3 rows architecture where:
1.  `title` + `location`
2.  `subTitle` (or `details` if no `subTitle`)
3.  `details` (if there is `subTitle`) + `statuses` (always on the last row in the right split by ` & `)
- updated storybook story of Teaser component. I created 3 stories:
1. all fields
2. with one status
3. without statuses
I had to do this, because in storybook we can't change count of array elements or remove array at all. Also I don't want to create some `withStatuses` boolean knob, because it doesn't represent any real component prop.

feat: add statuses to Teaser

---

src/components/Callout/Callout.scss
src/components/Callout/__tests__/__snapshots__/Callout.spec.js.snap

The Callout's content width fills a whole free width of Callout.

fix(Callout): stretch content on full width

---

src/components/ButtonGroup/ButtonGroup.scss
src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/__tests__/ButtonGroup.spec.js
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap

Adds `.ButtonGroup__button--first` and `.ButtonGroup__button--last` classnames for selecting the first and last buttons in a `ButtonGroup`, instead of relying on CSS pseudo-classes.

fix(ButtonGroup): add classnames to style first and last button

---

src/components/TwoPaneView/RightPane/RightPane.scss
src/components/TwoPaneView/TwoPaneView.scss
src/components/TwoPaneView/TwoPaneView.tsx
src/components/TwoPaneView/__tests__/__snapshots__/TwoPaneView.spec.js.snap
stories/TwoPaneView.tsx

fix(TwoPaneView): right pane doesn't jump too much on scroll

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/__tests__/Dropdown.spec.js
src/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
stories/Dropdown.tsx

The problem was in `children` prop type for Dropdown if you add as children mix of ListItem[] and single ListItem.
Example **(type error)**:
```
<Dropdown
button={<Button context="brand">Click me!</Button>}
onChange={mockOnChange}
placement="top-start"
>
<ListItem key="disabled-key" disabled>
Disabled
</ListItem>
{['one', 'two'].map((value) => (
<ListItem key={value} value={value}>
{value}
</ListItem>
))}
</Dropdown>
```
At the same type **no error** for:
```
<Dropdown
button={<Button context="brand">Click me!</Button>}
onChange={mockOnChange}
placement="top-start"
>
<ListItem key="disabled-key" disabled>
Disabled
</ListItem>
<ListItem key="disabled-key-2" disabled>
Disabled2
</ListItem>
</Dropdown>
```
or
```
<Dropdown
button={<Button context="brand">Click me!</Button>} …
```

fix(Dropdown): children type

---

src/components/Text/MarkedText/MarkedText.js
src/components/Text/MarkedText/__tests__/MarkedText.spec.js
src/components/Text/MarkedText/__tests__/__snapshots__/MarkedText.spec.js.snap

[ONEUI-263](https://jira.textkernel.nl/browse/ONEUI-263)

fix(MarkedText): fix issue with escaping of 's' character

---

src/components/SelectComponents/Autosuggest/Autosuggest.tsx
src/components/SelectComponents/Autosuggest/__tests__/Autosuggest.spec.js
src/components/SelectComponents/Autosuggest/__tests__/__snapshots__/Autosuggest.spec.js.snap
src/components/SelectComponents/ComboboxMulti/ComboboxMulti.tsx
src/components/SelectComponents/ComboboxMulti/__tests__/ComboboxMulti.spec.js
src/components/SelectComponents/ComboboxMulti/__tests__/__snapshots__/ComboboxMulti.spec.js.snap

feat(Autosuggest, Combobox): add prop to set HTML attributes on input element

---

src/components/LocationSelector/LocationSelector.tsx
src/components/LocationSelector/LocationSelectorDialog/LocationSelectorDialog.js
stories/LocationSelector.tsx

Story: [JF-2714](https://jira.textkernel.nl/browse/JF-2714)

feat(LocationSelector): add prop to set different input placeholder inside the modal

---

src/components/Tabs/TabItem/TabItem.tsx
src/components/Tabs/TabsBar/TabsBar.tsx
stories/Tabs.tsx

Improve TS typing in Tab components to allow specifying possible tab ids instead of generic `number | string`

feat(Tabs): allow passing custom TS types

---

src/components/SelectButtonGroup/SelectButton/SelectButton.scss
src/components/SelectButtonGroup/SelectButton/SelectButton.tsx
src/components/SelectButtonGroup/SelectButton/__tests__/SelectButton.spec.js
src/components/SelectButtonGroup/SelectButton/__tests__/__snapshots__/SelectButton.spec.js.snap
src/components/SelectButtonGroup/SelectButtonGroup/SelectButtonGroup.tsx
src/components/SelectButtonGroup/SelectButtonGroup/__tests__/SelectButtonGroup.spec.js
src/components/SelectButtonGroup/SelectButtonGroup/__tests__/__snapshots__/SelectButtonGroup.spec.js.snap
stories/SelectButtonGroup.tsx

This adds support for using this component with controlled data while preserving the possibility to use it in an uncontrolled way. Following the API changes, (default) values are meant to be defined on `SelectButtonGroup`. Use `value` in a controlled implementation, or `defaultValue` when uncontrolled. Context (prop is renamed to `context`) can be defined both on `SelectButtonGroup` level (applies to all children) or on each `SelectButton` individually.
BREAKING CHANGE: The API for these components is changed because of the improvements and changes in behavior that are implemented.

feat(SelectButtonGroup): add support for controlled behavior and improve API

---

src/components/Footer/Footer.tsx
src/components/Footer/__tests__/Footer.spec.js
src/components/Footer/__tests__/__snapshots__/Footer.spec.js.snap

Hardcoded `new Date().getFullYear();` caused test failure

fix(Footer): add year prop to Footer component to make it determenistic

---

src/components/Sliders/Slider.scss

Adjust the alignment of slider handles so they are vertically positioned in the middle of the slider rail

fix(Sliders): vertically align handles in the middle of the rail

---

package.json
src/components/Link/Link.scss
src/components/Link/Link.tsx
stories/Link.tsx

We encountered several places where we use Link in the navigation. We always had to implement extra logic, and html elements to get rid of the text highlighting on hover. It will be much cleaner when it is implemented here.

feat(Link): Add prop to disable text decoration on hover

---

package-lock.json
package.json

We cannot update OneUI because of outdated peer dependency. This PR update the dependency declaration to work with newer versions too.
```
ngui|develop ⇒ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: jobfeed-ngui@0.0.1
npm ERR! Found: react-icons@4.3.1
npm ERR! node_modules/react-icons
npm ERR!   react-icons@"^4.3.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-icons@"^3.7.0" from @textkernel/oneui@17.2.0
npm ERR! node_modules/@textkernel/oneui
npm ERR!   @textkernel/oneui@"^17.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially …
```

chore: change declaration for peer dependencies

---

src/themes/oneui/base-variables/_typography.scss

fix: added missed px unit in font-size-large

---

src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/__tests__/__snapshots__/Checkbox.spec.js.snap
src/components/LabelPicker/LabelPicker.scss
src/components/LabelPicker/LabelPicker.tsx
src/components/LabelPicker/__tests__/__snapshots__/LabelPicker.spec.js.snap
src/components/ProductTour/__tests__/__snapshots__/ProductTour.spec.js.snap
stories/Checkbox.tsx
stories/LabelPicker.tsx

When using checkboxes in LabelPicker in browsers that show scroll bars in the traditional way (not as overlays) the layout breaks and labels are displayed in a separate line from the checkbox itself. In order to fix this, we need the checkbox to be in a flexbox. However, this as default behaviour can negatively effect already existing implementations. Hence this option is added via a new prop. 
This new prop is now used in LabelPicker.
This PR also fixes a small bug with passing `style` and `className` to Checkbox that were applied to the wrong HTML element.

feat(Checkbox): add `asFlexbox` prop to allow for different layout styles

---

src/components/Teaser/Teaser.tsx
src/components/Teaser/__tests__/Teaser.spec.js
src/components/Teaser/__tests__/__snapshots__/Teaser.spec.js.snap
stories/Teaser.tsx

Add a prop to disabled styling for Teaser, where all text is in muted color. 
See [JF-3008 ](https://textkernel.atlassian.net/browse/JF-3008)for details

feat(Teaser): add prop for disabled styling

---

src/components/Map/Map/Map.tsx

When adding a single point marker to the map, it automatically zoomed to max closeness. This view is hard to see, so now it zooms in a way that you can still see some context

fix(Map): zoom map to reasonable view when using a single point marker

---

src/components/Tag/Tag.tsx
src/components/Tag/__tests__/Tag.spec.js
src/components/Tag/__tests__/__snapshots__/Tag.spec.js.snap
stories/atoms/Tag.tsx

Story: [JF-3493](https://textkernel.atlassian.net/browse/JF-3493)
* Allow forward ref for Tag so it can be rendered in a Tooltip
* Add className and style props that will pass to the Text that wraps the child

feat(Tag): extend API with styling options and ForwardRef

---

.storybook/main.js

Fix Storybook built that prevented it from being deployed during 18.8.0 release

chore: fix storybook build

---

src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/__tests__/ButtonGroup.spec.tsx
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.tsx.snap

fix: buttongroup context isn't passed to the button

---

src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/__tests__/RadioButton.spec.tsx
src/components/RadioButton/__tests__/__snapshots__/RadioButton.spec.tsx.snap

In one of the recent refactors a bug was introduced where styles for disabled RadioButton were not applied. This ticket reinstate those styles.

fix(RadioButton): wrongly styled when disabled

---

src/components/TextArea/TextArea.tsx

After migrating to TS, types were too generic and things like `maxLength` throw TS errors. This PR fixes that.
Note: for some reason errors were not visible in Storybook. Perhaps something we should look into later.

fix(TextArea): component types to be specific

---

src/themes/oneui/base-variables/_colors.scss

Fix for deprecation warning in tests:
```
DEPRECATION WARNING: $weight: Passing a number without unit % (50) is deprecated.
To preserve current behavior: $weight * 1%
More info: https://sass-lang.com/d/function-units
╷
73 │               --color-#{ $context }-#{ 50 - math.div($factor, 2) }: #{mix(
│ ┌─────────────────────────────────────────────────────────────────────^
74 │ │                 $color-background,
75 │ │                 $value,
76 │ │                 $factor
77 │ │             )};
│ └─────────────^
╵
src/themes/oneui/base-variables/_colors.scss 73:69  @import
src/themes/oneui/oneui.scss 1:9                     @import
src/components/Dialogs/Dialog/Dialog.scss 1:9       root stylesheet
```

fix(scss): deprecation errors after color changes

---

src/__mocks__/svgMock.js
src/components/Link/Link.scss
src/components/Link/Link.tsx
src/components/Link/__tests__/Link.spec.tsx
src/components/Link/__tests__/__snapshots__/Link.spec.tsx.snap
src/components/SelectBadge/__tests__/__snapshots__/SelectBadge.spec.tsx.snap
src/components/Toaster/__tests__/__snapshots__/Toast.spec.tsx.snap

Story: [ONEUI-477](https://textkernel.atlassian.net/browse/ONEUI-477)
BREAKING CHANGE: `context` and `doNotDecorateOnHover` props are no longer supported for Link component

feat(Link): implement new design

---

src/components/FieldWithValidation/__tests__/FieldWithValidation.spec.tsx
src/components/FieldWithValidation/__tests__/__snapshots__/FieldWithValidation.spec.tsx.snap
src/components/Input/Input.scss
src/components/Input/Input.tsx
src/components/Input/__tests__/Input.spec.tsx
src/components/Input/__tests__/__snapshots__/Input.spec.tsx.snap
src/components/Themeroller/ThemeTuner/ItemValue/ColorValue/__tests__/__snapshots__/ColorValue.spec.tsx.snap
src/components/Themeroller/ThemeTuner/ItemValue/NumberValue/__tests__/__snapshots__/NumberValue.spec.tsx.snap
src/components/Themeroller/ThemeTuner/ItemValue/StringValue/__tests__/__snapshots__/StringValue.spec.tsx.snap
src/components/Themeroller/ThemeTuner/ItemValue/UnitValue/__tests__/__snapshots__/UnitValue.spec.tsx.snap
src/components/Themeroller/ThemeTuner/__tests__/__snapshots__/ThemeTuner.spec.tsx.snap
src/components/Themeroller/__tests__/__snapshots__/Themeroller.spec.tsx.snap
stories/atoms/Input.stories.tsx
stories/packages/LocationSelectorUtils.stories.tsx

[ONEUI-455](https://textkernel.atlassian.net/browse/ONEUI-455)
BREAKING CHANGE: Input component props size, context, and additional states are updated
- size prop options are limited to `small` or `medium`, with `medium` as the default. The options `large` and `normal` have been removed. Replace size="large" or omitting size (previously defaulting to `normal`) with size="medium", or use size="small" as needed.
- context prop only accepts `critical`. Other contexts like `brand` or `success` are removed. For critical contexts, use context="critical" and provide an errorMessage. 
- new `readOnly` prop added to specify if the input field should be non-editable. Replace any custom methods for setting inputs as non-editable with readOnly={true}.
- new `reserveErrorMessageSpace` prop added …

feat(Input): migrate to new design
