textkernel/oneui

etc/webpack/webpack.config.js

Fix bug in webpack config

---

README.md
src/README.md

Adds a readme about guidelines for working on implementation of new components.

Added README for DoD guidelines

---

.eslintrc.json
src/components/Alert/Alert.js
src/components/Alert/Alert.scss
src/components/Alert/__tests__/Alert.spec.js
src/components/Alert/__tests__/__snapshots__/Alert.spec.js.snap
src/components/Alert/index.js
src/index.js
stories/Alert.js
stories/index.js

* Adds an Alert component with tests and story

Implemented Alert component

---

.eslintrc.json
.storybook/preview-head.html
src/components/Heading/Heading.js
src/components/Heading/Heading.scss
src/components/Heading/__tests__/Heading.spec.js
src/components/Heading/__tests__/__snapshots__/Heading.spec.js.snap
src/components/Heading/index.js
src/components/Text/Text.js
src/components/Text/Text.scss
src/components/Text/__tests__/Text.spec.js
src/components/Text/__tests__/__snapshots__/Text.spec.js.snap
src/components/Text/index.js
src/constants/style-related.js
src/index.js
src/themes/nice/base-variables/_colors.scss
src/themes/nice/base-variables/_typography.scss
stories/Heading.js
stories/Text.js
stories/index.js

* Implements a Heading component that renders h1...h4
* Implements a Text component that renders a paragraph or span (if inline)
* Adds `color-muted` (doesn't need shades, we already have `color-neutral` that comes with 4 shades)

Heading & Text component

---

src/components/Alert/Alert.scss

Slightly updated alert styling with box shadow

Alert style update

---

src/components/Alert/Alert.scss

Alert background is currently transparent, added a background color

Alert background color

---

etc/webpack/utils/utils.js
etc/webpack/webpack.config.js

* Bring autoprefixer back
* Remove hash appending to classnames for dev env

Update webpack configuration

---

src/components/Button/Button.scss
src/components/Link/Link.js
src/components/Link/Link.scss
src/components/Link/__tests__/Link.spec.js
src/components/Link/__tests__/__snapshots__/Link.spec.js.snap
src/components/Link/index.js
src/index.js
src/themes/nice/base-variables/_colors.scss
stories/Link.js
stories/index.js

* Adds Link component that renders an `a`-element

Link component

---

src/components/Button/Button.js
src/components/Button/Button.scss
src/components/Button/__tests__/Button.spec.js
src/components/Button/__tests__/__snapshots__/Button.spec.js.snap
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap
src/components/Input/Input.js
src/components/Input/Input.scss
src/components/Input/__tests__/Input.spec.js
src/components/Input/__tests__/__snapshots__/Input.spec.js.snap
src/components/Input/index.js
src/constants/index.js
src/themes/nice/base-variables/_sizing.scss
src/themes/nice/base-variables/_typography.scss
stories/Input.js
stories/index.js

Input component

---

src/components/LoadingSpinner/LoadingSpinner.js
src/components/LoadingSpinner/LoadingSpinner.scss
src/components/LoadingSpinner/__tests__/LoadingSpinner.spec.js
src/components/LoadingSpinner/__tests__/__snapshots__/LoadingSpinner.spec.js.snap
src/components/LoadingSpinner/index.js
src/index.js
stories/LoadingSpinner.js
stories/index.js

* Adds a LoadingSpinner component with only context and custom size props (to be extended when necessary)

Loading spinner component

---

src/components/ProgressBar/ProgressBar.js
src/components/ProgressBar/ProgressBar.scss
src/components/ProgressBar/__tests__/ProgressBar.spec.js
src/components/ProgressBar/__tests__/__snapshots__/ProgressBar.spec.js.snap
src/components/ProgressBar/index.js
src/index.js
src/themes/nice/base-variables/_misc.scss
src/themes/nice/base-variables/_miscellaneous.scss
src/themes/nice/nice.scss
stories/ProgressBar.js
stories/index.js

ProgressBar component

---

.storybook/addons.js
.storybook/config.js
package-lock.json
package.json
stories/.eslintrc.json
stories/Alert.js
stories/Button.js
stories/Checkbox.js
stories/Input.js
stories/RadioButton.js
stories/Tabs.js
stories/TextArea.js

* Added `@storybook/addon-actions`, `@storybook/addon-console` to enable logging any console events to action logger

Enable Storybook action logger

---

src/packages/bem/__tests__/bem.spec.js
src/packages/bem/__tests__/dummy-components/Button/Button.jsx
src/packages/bem/__tests__/dummy-components/Button/classnamesMap.json
src/packages/bem/__tests__/dummy-components/ButtonStateless/ButtonStateless.jsx
src/packages/bem/__tests__/dummy-components/ButtonStateless/classnamesMap.json
src/packages/bem/bemUtils.js

Issue: https://trello.com/c/sAgax2Ir/42-fix-bug-in-bemjs-about-building-classnames-with-numeric-mods

Fix bug in bem.js about building classnames with numeric mods

---

.eslintignore
.travis.yml
README.md
package-lock.json
package.json

* Run CI with coverage reporting
* Integrate with [coveralls.io](https://coveralls.io)
* Add coverage badge to README.md
* Add dependencies badge to README.md
Note that the badge will say 'coverage unknown' until this has been merged with `master`

Set up Coveralls reporting

---

.gitignore
package-lock.json
package.json
src/components/Alert/Alert.js
src/components/Button/Button.js
src/components/ButtonGroup/ButtonGroup.js
src/components/CandidateAvatar/CandidateAvatar.js
src/components/Checkbox/Checkbox.js
src/components/Heading/Heading.js
src/components/Input/Input.js
src/components/Link/Link.js
src/components/LoadingSpinner/LoadingSpinner.js
src/components/ProgressBar/ProgressBar.js
src/components/Tabs/Tab/Tab.js
src/components/Tabs/TabContent/TabContent.js
src/components/Tabs/TabItem/TabItem.js
src/components/Tabs/TabMenu/TabMenu.js
src/components/Tabs/Tabs.js
src/components/Text/Text.js
src/components/TextArea/TextArea.js
stories/CandidateAvatar.js

**NOTE**
~~Do not merge before [`add-release-presequisites`](https://github.com/textkernel/oneui/pull/46)~~ Ignore - PR has been merged.
Running `npm run storybook:deploy` will build and deploy Storybook from current `master` to [Github Pages](https://textkernel.github.io/oneui/)
* Added `@storybook/storybook-deployer` and reconfigured `package.json` to include `storybook:deploy` script
* Added `displayName` to all components because component names would get minified (not applied to Dummy component as it is to be removed in another branch)

Deploy Storybook to Github Pages

---

src/components/Alert/__tests__/__snapshots__/Alert.spec.js.snap
src/components/Button/__tests__/__snapshots__/Button.spec.js.snap
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap
src/components/CandidateAvatar/__tests__/__snapshots__/CandidateAvatar.spec.js.snap
src/components/Heading/__tests__/__snapshots__/Heading.spec.js.snap
src/components/Input/__tests__/__snapshots__/Input.spec.js.snap
src/components/LoadingSpinner/__tests__/__snapshots__/LoadingSpinner.spec.js.snap
src/components/ProgressBar/__tests__/__snapshots__/ProgressBar.spec.js.snap
src/components/TextArea/__tests__/__snapshots__/TextArea.spec.js.snap
src/packages/bem/README.md
src/packages/bem/__tests__/bem.spec.js
src/packages/bem/__tests__/dummy-components/Button/classnamesMap.json
src/packages/bem/__tests__/dummy-components/ButtonStateless/classnamesMap.json
src/packages/bem/bemUtils.js

Applied if modifier has any value

Add ability to define "wildcard" class name for modifier

---

package.json

* Changes `prepare` script to `prepublishOnly`

Change prepare to prepublishOnly

---

src/components/CandidateAvatar/__tests__/CandidateAvatar.spec.js
src/components/Tabs/Tab/__tests__/Tab.spec.js
src/components/Tabs/Tab/__tests__/__snapshots__/Tab.spec.js.snap
src/components/Tabs/Tabs.js
src/components/Tabs/__tests__/Tabs.spec.js

Slightly improved codecov for Tabs and CandidateAvatar components

Improve code coverage

---

src/components/Checkbox/__tests__/__snapshots__/Checkbox.spec.js.snap
src/components/LoadingSpinner/__tests__/__snapshots__/LoadingSpinner.spec.js.snap
src/components/RadioButton/__tests__/__snapshots__/RadioButton.spec.js.snap
src/components/Text/Text.js
src/components/Text/Text.scss
src/components/Text/__tests__/Text.spec.js
src/components/Text/__tests__/__snapshots__/Text.spec.js.snap
stories/Text.js

* Added `size` prop for Text component (small / normal / large)

Text improvements

---

package.json
src/components/List/List.js
src/components/List/List.scss
src/components/List/ListActions/ListActions.js
src/components/List/ListActions/ListActions.scss
src/components/List/ListActions/__tests__/ListActions.spec.js
src/components/List/ListActions/__tests__/__snapshots__/ListActions.spec.js.snap
src/components/List/ListActions/index.js
src/components/List/ListItem/ListItem.js
src/components/List/ListItem/ListItem.scss
src/components/List/ListItem/__tests__/ListItem.spec.js
src/components/List/ListItem/__tests__/__snapshots__/ListItem.spec.js.snap
src/components/List/ListItem/index.js
src/components/List/__tests__/List.spec.js
src/components/List/__tests__/__snapshots__/List.spec.js.snap
src/components/List/index.js
src/index.js
src/themes/oneui/base-variables/_colors.scss
stories/List.js
stories/index.js

[ONEUI-33](https://jira.textkernel.nl/browse/ONEUI-33)

WIP: List, ListItem and ListActions

---

.travis.yml

* Deploy Storybook to Github Pages when new tag is pushed

Storybook CD

---

src/components/Tabs/Tabs.js

Tabs: don't .bind() `this` on component methods, use arrow functions instead.

Tabs improvement

---

src/components/List/__tests__/List.spec.js

Suppress expected console error in List.spec.js by mocking its implementation

test: mock console error implementation in list test

---

CONTRIBUTING.md
RELEASING.md

Add RELEASING.md file describing specifications for version numbering and release procedure

docs(releasing): describe procedure for making new release

---

src/components/List/ListItem/ListItem.js
src/components/List/ListItem/ListItem.scss
src/components/List/__tests__/__snapshots__/List.spec.js.snap
stories/List.js

[JF-1459](https://jira.textkernel.nl/browse/JF-1459) Adds disabled option to ListItem where item is not highlighted on hover

add disabled option to ListItem

---

src/components/Alert/__tests__/__snapshots__/Alert.spec.js.snap
src/components/Button/Button.js
src/components/Button/Button.scss
src/components/Button/__tests__/Button.spec.js
src/components/Button/__tests__/__snapshots__/Button.spec.js.snap
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap
stories/Button.js

[ONEUI-44](https://jira.textkernel.nl/browse/ONEUI-44)

render button as ancor when href is defined

---

src/components/ButtonGroup/ButtonGroup.js
src/components/ButtonGroup/ButtonGroup.scss
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap
stories/ButtonGroup.js

[ONEUI-45](https://jira.textkernel.nl/browse/ONEUI-45)

Add inline option to ButtonGroup

---

.storybook/preview-head.html
src/components/Heading/Heading.scss
src/themes/oneui/base-variables/_typography.scss

[ONEUI-46](https://jira.textkernel.nl/browse/ONEUI-46)

adjust heading variables

---

.gitignore
etc/webpack/webpack.config.js
etc/webpack/webpack.dev.config.js
etc/webpack/webpack.prod.config.js
package-lock.json
package.json
src/components/Pagination/Pagination.js

Fix: move react, react-dom and prop-types to be peer-dependencies and not to bundle with package.

Fix: move general dependencies to peer-dependencies

---

src/components/Alert/Alert.js
src/components/Alert/__tests__/__snapshots__/Alert.spec.js.snap
src/components/ButtonGroup/ButtonGroup.js
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap
src/components/LoadingSpinner/LoadingSpinner.js
src/components/LoadingSpinner/__tests__/__snapshots__/LoadingSpinner.spec.js.snap
src/components/ProgressBar/ProgressBar.js
src/components/ProgressBar/__tests__/__snapshots__/ProgressBar.spec.js.snap
src/components/Tabs/TabContent/TabContent.js
src/components/Tabs/TabContent/__tests__/__snapshots__/TabContent.spec.js.snap
src/components/Tabs/TabItem/TabItem.js
src/components/Tabs/TabItem/__tests__/__snapshots__/TabItem.spec.js.snap
src/components/Tabs/TabMenu/TabMenu.js
src/components/Tabs/TabMenu/__tests__/__snapshots__/TabMenu.spec.js.snap
src/components/Tabs/Tabs.js
src/components/Tabs/__tests__/__snapshots__/Tabs.spec.js.snap

Various accessibility improvements

fix(a11y): accessibility improvements

---

src/components/Chip/Chip.js
src/components/Chip/Chip.scss
src/components/Chip/__tests__/Chip.spec.js
src/components/Chip/__tests__/__snapshots__/Chip.spec.js.snap
src/components/Chip/index.js
src/index.js
src/themes/oneui/base-variables/_typography.scss
stories/Chip.js
stories/index.js

[[ONEUI-52]](https://jira.textkernel.nl/browse/ONEUI-52) Added a component to render simple chips

feat: chip component

---

CHANGELOG.md
CONTRIBUTING.md
RELEASING.md
package-lock.json
package.json

* Set up and configure standard-version
* Generate initial changelog
* Update releasing and contributing docs

feat(workflow): set up standard-version and update docs

---

src/components/ButtonGroup/ButtonGroup.js
src/components/ButtonGroup/ButtonGroup.scss
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap

fix(ButtonGroup): style fixes

---

src/components/Footer/Footer.js
src/components/Footer/Footer.scss
src/components/Footer/__tests__/__snapshots__/Footer.spec.js.snap
src/components/Header/Header.js
src/components/Header/Header.scss
src/components/Header/__tests__/__snapshots__/Header.spec.js.snap
src/components/Navigation/NavBar/NavBar.js
src/components/Navigation/NavBar/NavBar.scss
src/components/Navigation/NavBar/__tests__/__snapshots__/NavBar.spec.js.snap
src/components/PageWidthRestrictor/PageWidthRestrictor.js
src/components/PageWidthRestrictor/PageWidthRestrictor.scss
src/components/PageWidthRestrictor/index.js
src/index.js
src/themes/oneui/base-variables/_sizing.scss
stories/PageWidthRestrictor.js
stories/index.js

BREAKING CHANGE: variable `--site-container-size` is deprecated in favor of `--site-container-min-size`, `--site-container-max-size` and `--site-container-padding`. Recommended new usage  through `<PageWidthRestrictor>`.

feat: add container variables to make it a bit responsive

---

src/components/Footer/Footer.scss
src/components/Header/Header.scss

Story: [ONEUI-62](https://jira.textkernel.nl/browse/ONEUI-62)

fix(Header, Footer): Adjust styling to match designs

---

src/components/List/List.js
src/components/List/List.scss
src/components/List/ListItem/ListItem.js
src/components/List/ListItem/ListItem.scss
src/components/List/ListItem/__tests__/__snapshots__/ListItem.spec.js.snap
src/components/List/__tests__/List.spec.js
src/components/List/__tests__/__snapshots__/List.spec.js.snap
src/constants/index.js
src/themes/oneui/base-variables/_colors.scss

* Add keyboard navigation
* Add tests coverage
* Fix color shades for the selected and highlighted items in the list

1460 keyboard navigation

---

package-lock.json
package.json
src/components/Modal/Modal.js
src/components/Modal/Modal.scss
src/components/Modal/__tests__/Modal.spec.js
src/components/Modal/__tests__/__snapshots__/Modal.spec.js.snap
src/components/Modal/index.js
src/index.js
src/utils/OneUI/OneUI.js
stories/Modal.js
stories/index.js

Story: [ONEUI-67](https://jira.textkernel.nl/browse/ONEUI-670)

feat(component): new Modal component

---

src/components/Autosuggest/Autosuggest.js
src/components/Autosuggest/Autosuggest.scss
src/components/Autosuggest/__tests__/__snapshots__/Autosuggest.spec.js.snap
src/components/FieldWrapper/FieldWrapper.js
src/components/FieldWrapper/FieldWrapper.scss
src/components/FieldWrapper/__tests__/__snapshots__/FieldWrapper.spec.js.snap
src/index.js
stories/Autosuggest.js
stories/FieldWrapper.js
stories/index.js

Story: [JF-1708](https://jira.textkernel.nl/browse/JF-1708)

fix(Autosuggest): styles and behaviour adjustments

---

package-lock.json
package.json
src/__mocks__/googleApiMock.js
src/components/Map/Map.js
src/components/Map/MapWithGoogleLoader.js
src/components/Map/__mocks__/geocodeResponse.json
src/components/Map/__tests__/Map.spec.js
src/components/Map/__tests__/__snapshots__/Map.spec.js.snap
src/components/Map/__tests__/__snapshots__/MapWithGoogleLoader.spec.js.snap
stories/Map.js

Story: [ONEUI-85](https://jira.textkernel.nl/browse/ONEUI-85)
BREAKING CHANGE: `center` and `zoom` props have been deprecated in favour of `defaultArea` that supports also fitting map boundaries based on address lookup

 feat(Map): add option to fit map to address as default view

---

src/components/Slider/Slider.scss

fix(Slider): update styling

---

src/components/Drawer/Drawer.js
src/components/Drawer/Drawer.scss
src/components/Drawer/__tests__/Drawer.spec.js
src/components/Drawer/__tests__/__snapshots__/Drawer.spec.js.snap
src/components/Drawer/index.js
src/index.js
src/themes/oneui/base-variables/_misc.scss
stories/Drawer.js
stories/index.js

- a mobile version will be implemented later

feat(component) new Drawer component

---

src/components/Pill/PillButton/PillButton.scss

Some styling tweaks for PillButton (to be merged back into `93-pill-button` once reviewed & finished)

WIP: PillButton CSS tweaks

---

src/components/Pill/Pill.js
src/components/Pill/PillButton/PillButton.js
src/components/Pill/PillButton/PillButton.scss
src/components/Pill/PillButton/__tests__/PillButton.spec.js
src/components/Pill/PillButton/__tests__/__snapshots__/PillButton.spec.js.snap
src/components/Pill/PillButton/index.js
src/components/Pill/index.js
src/index.js
src/themes/oneui/base-variables/_typography.scss
stories/Pill.js
stories/index.js

Story: [ONEUI-93](https://jira.textkernel.nl/browse/ONEUI-93)

feat(Pill): new component PillButton

---

package-lock.json
package.json
src/__mocks__/popper.js.js
src/components/PopupBase/PopupBase.js
src/components/PopupBase/__mocks__/PopoverDummy.js
src/components/PopupBase/__tests__/PopupBase.spec.js
src/components/PopupBase/__tests__/__snapshots__/PopupBase.spec.js.snap
src/components/PopupBase/index.js
src/constants/autocomplete.js
src/constants/component-specific.js
src/constants/index.js
src/index.js
stories/PopupBase.js
stories/index.js

Story: [ONEUI-98](https://jira.textkernel.nl/browse/ONEUI-98)

feat: new PopupBase component

---

src/components/List/List.js
src/components/List/__tests__/List.spec.js
src/components/List/__tests__/__snapshots__/List.spec.js.snap
src/utils/scrollIntoViewIfNeeded.js
stories/List.js

Story: [JF-1780](https://jira.textkernel.nl/browse/JF-1780)

fix(List): keyboard navigation bugs

---

src/components/Pill/PillDropdown/PillDropdown.js
src/components/Pill/PillDropdown/PillDropdown.scss
src/components/Pill/PillDropdown/__tests__/__snapshots__/PillDropdown.spec.js.snap
src/components/Pill/__tests__/__snapshots__/Pill.spec.js.snap

Story: [JF-1877](https://jira.textkernel.nl/browse/JF-1877)

fix(PillDropdown): add z-index so that it always appears on top

---

package.json
scripts/check-npm-publish-access/check-npm-publish-access.sh

build: implemented script that checks npm access before publishing

---

src/components/Buttons/SearchButton/SearchButton.js
src/components/Buttons/SearchButton/SearchButton.scss
src/components/Buttons/SearchButton/__tests__/SearchButton.spec.js
src/components/Buttons/SearchButton/__tests__/__snapshots__/SearchButton.spec.js.snap
stories/Button.js

Story [JF-1907](https://jira.textkernel.nl/browse/JF-1907)

feat(SearchButton): Extend SearchButton with an optional label

---

src/packages/storybook/withStore/__tests__/withStore.spec.js
src/packages/storybook/withStore/withStore.js
stories/Autosuggest.js

Story: [ONEUI-90](https://jira.textkernel.nl/browse/ONEUI-90)

fix(storybook): fix error in Autosuggest story

---

.storybook/preview-head.html
src/themes/oneui/base-variables/_typography.scss

Story: [ONEUI-58](https://jira.textkernel.nl/browse/ONEUI-58)

feat(fonts): change default font-family to use system fonts

---

src/components/LocationSelector/__tests__/__snapshots__/LocationSelector.spec.js.snap
src/components/Modal/Modal.js
src/components/Modal/__tests__/Modal.spec.js
src/components/Modal/__tests__/__snapshots__/Modal.spec.js.snap

Story: [ONEUI-105](https://jira.textkernel.nl/browse/ONEUI-105)

fix(Modal): ensure that classNames from props are applied as intended

---

src/components/Pill/Pill.js
src/components/Pill/__tests__/Pill.spec.js
src/components/Pill/__tests__/__snapshots__/Pill.spec.js.snap
src/components/PopupBase/PopupBase.js
src/components/PopupBase/__tests__/PopupBase.spec.js
src/components/PopupBase/__tests__/__snapshots__/PopupBase.spec.js.snap
src/components/Tooltip/__tests__/__snapshots__/Tooltip.spec.js.snap
stories/Pill.js
stories/PopupBase.js

Story: [JF-1975](https://jira.textkernel.nl/browse/JF-1975)

feat(Pill): add onClose prop

---

src/components/Buttons/Button/Button.tsx
src/components/Callout/Callout.tsx
src/components/SelectedOption/SelectedOption.scss
src/components/SelectedOption/SelectedOption.tsx
src/components/SelectedOption/__tests__/SelectedOption.spec.js
src/components/SelectedOption/__tests__/__snapshots__/SelectedOption.spec.js.snap
src/components/SelectedOption/index.ts
src/components/Tooltip/Tooltip.tsx
src/index.ts
src/types/types.d.ts
stories/SelectedOption.tsx
stories/index.ts

Story: [ONEUI-113](https://jira.textkernel.nl/browse/ONEUI-113)

feat: new SelectedOption component

---

src/components/LocationSelector/LocationSelector.js
src/components/LocationSelector/LocationSelectorDialog/LocationSelectorDialog.js
src/components/LocationSelector/LocationSelectorDialogWithGoogleLoader/LocationSelectorDialogWithGoogleLoader.js
stories/LocationSelector.js

Story: [ONEUI-118](https://jira.textkernel.nl/browse/ONEUI-118)

fix(LocationSelector): add initialMapAddress prop

---

.babelrc
README.md
package.json
scripts/build/webpack.prod.config.js
tsconfig.json

Story: [ONEUI-75](https://jira.textkernel.nl/browse/ONEUI-75)

build: bundle size improvements

---

src/components/Autosuggest/Autosuggest.js

Story: [ONEUI-127](https://jira.textkernel.nl/browse/ONEUI-127)

fix(Autosuggest): cannot delete item tags by clicking them

---

scripts/build/utils/utils.js

Story [ONEUI-130](https://jira.textkernel.nl/browse/ONEUI-130)

fix(Slider): Fix slider appearing

---

package-lock.json
package.json
src/components/LocationAutocomplete/index.js
src/components/LocationSelector/index.js
stories/Tabs.tsx

update prettier to latest version so that it supports optional chaining correctly

build(lint): update prettier

---

stories/SelectButtonGroup.tsx

fix(SelectButtonGroup): remove knob that doesn't work from story

---

src/components/Autosuggest/Autosuggest.js
src/components/Autosuggest/__tests__/Autosuggest.spec.js

Story: [ONEUI-129](https://jira.textkernel.nl/browse/ONEUI-129)

fix(Autosuggest): allow selection of same item twice in a row

---

src/components/PopupBase/PopupBase.js
src/components/SelectedOption/SelectedOption.tsx
src/components/SelectedOption/__tests__/__snapshots__/SelectedOption.spec.js.snap

fix: put onClose invocation before closing the dropdown for PopupBase component

---

src/components/FieldWithValidation/__tests__/__snapshots__/FieldWithValidation.spec.js.snap
src/components/Input/Input.scss
src/components/Input/Input.tsx
src/components/Input/__tests__/Input.spec.js
src/components/Input/__tests__/__snapshots__/Input.spec.js.snap
src/themes/oneui/base-variables/_typography.scss
stories/Input.tsx

Story [ONEUI-165](https://jira.textkernel.nl/browse/ONEUI-165)

feat(Input): Add an optional label

---

src/components/Field/Field.tsx
src/components/Field/__tests__/Field.spec.js
src/components/Field/__tests__/__snapshots__/Field.spec.js.snap

Adds `...rest` parameter to `label` element to apply additional attributes

fix(Field): Add rest parameter

---

src/components/List/ListOptimizer/__tests__/ListOptimizer.spec.js
src/components/List/ListOptimizer/__tests__/__snapshots__/ListOptimizer.spec.js.snap
src/components/Select/SuggestionsList/SuggestionsList.tsx
src/components/Select/SuggestionsList/__tests__/__snapshots__/SuggestionsList.spec.js.snap
src/components/TwoPaneView/TwoPaneView.tsx
src/components/TwoPaneView/__tests__/__snapshots__/TwoPaneView.spec.js.snap

Story: [ONEUI-173](https://jira.textkernel.nl/browse/ONEUI-173)

fix: fixed all console errors and warnings when running tests

---

src/components/Autosuggest/Autosuggest.scss

Story [https://jira.textkernel.nl/browse/ONEUI-182](ONEUI-182)

fix: fixed z-index of autosuggest input

---

package-lock.json
package.json
src/components/Autosuggest/__tests__/__snapshots__/Autosuggest.spec.js.snap
src/components/FieldWrapper/FieldWrapper.js
src/components/FieldWrapper/__tests__/__snapshots__/FieldWrapper.spec.js.snap
src/components/LocationAutocomplete/__tests__/__snapshots__/LocationAutocomplete.spec.js.snap
src/components/LocationSelector/LocationSelectorDialog/__tests__/__snapshots__/LocationSelectorDialog.spec.js.snap
src/components/LocationSelector/__tests__/__snapshots__/LocationSelector.spec.js.snap
src/components/Select/AutosuggestMulti/AutosuggestMulti.scss
src/components/Select/AutosuggestMulti/AutosuggestMulti.tsx
src/components/Select/AutosuggestMulti/__tests__/AutosuggestMulti.spec.js
src/components/Select/AutosuggestMulti/__tests__/__snapshots__/AutosuggestMulti.spec.js.snap
src/components/Select/ComboboxMulti/ComboboxMulti.tsx
src/components/Select/ComboboxMulti/__tests__/ComboboxMulti.spec.js
src/components/Select/ComboboxMulti/__tests__/__snapshots__/ComboboxMulti.spec.js.snap
src/components/Select/SelectBase/SelectBase.tsx
src/components/Select/SelectBase/__tests__/__snapshots__/SelectBase.spec.js.snap
src/components/Select/SelectBase/interfaces.ts
stories/Select.tsx

BREAKING CHANGE: logic with deleting selection was moved to onSelectionRemove callback in AutosuggestMulti

feat(component): polishing autocompletemulti

---

src/components/LocationSelector/LocationSelector.tsx
src/components/LocationSelector/__tests__/__snapshots__/LocationSelector.spec.js.snap
src/components/LocationSelector/__tests__/utils.spec.js
src/components/LocationSelector/utils.ts
stories/LocationSelector.tsx

Story [ONEUI-185](https://jira.textkernel.nl/browse/ONEUI-185)

feat(LocationSelector): Added an option of fetching postal code of selected location

---

src/components/Select/AutosuggestMulti/AutosuggestMulti.tsx
src/components/Select/AutosuggestMulti/__tests__/AutosuggestMulti.spec.js
src/components/Select/AutosuggestMulti/__tests__/__snapshots__/AutosuggestMulti.spec.js.snap
src/components/Select/ComboboxMulti/ComboboxMulti.tsx
src/components/Select/ComboboxMulti/__tests__/__snapshots__/ComboboxMulti.spec.js.snap
src/components/Select/SelectBase/SelectBase.scss
src/components/Select/SelectBase/SelectBase.tsx
src/components/Select/SelectBase/__tests__/SelectBase.spec.js
src/components/Select/SelectBase/__tests__/__snapshots__/SelectBase.spec.js.snap
src/components/Select/SelectBase/interfaces.ts
src/components/Select/SuggestionsList/SuggestionsList.scss
src/components/Select/SuggestionsList/SuggestionsList.tsx
src/components/Select/SuggestionsList/__tests__/SuggestionsList.spec.js
src/components/Select/SuggestionsList/__tests__/__snapshots__/SuggestionsList.spec.js.snap
stories/Select.tsx

Improvements:
- 'isLoading' added support loading state;
- 'suggestionItemRenderer' prop defines render function for suggestion item;
- the first item doesn't have default highlighting while input empty. The highlighting appears only when a user typing something in the input;

feat(AutosuggestMulti): improve component to autosuggest requirements

---

src/components/LocationSelector/LocationSelector.scss
src/components/LocationSelector/LocationSelector.tsx
src/components/LocationSelector/__tests__/LocationSelector.spec.js
src/components/LocationSelector/__tests__/__snapshots__/LocationSelector.spec.js.snap
stories/LocationSelector.tsx

* Fix modal opening on form submitting
* Fix background color of the main input button

fix(LocationSelector): fix modal opening on form submitting

---

src/components/LocationSelector/LocationSelector.tsx
src/hooks/index.ts
src/hooks/useBrowserTabVisibilityChange.ts
stories/LocationSelector.tsx

Story [ONEUI-193](https://jira.textkernel.nl/browse/ONEUI-193)

fix(LocationSelector): fixed a bug where a modal got opened during tab switching

---

renovate.json

* Reduce PR noise by grouping and auto-merging certain dependencies
* Schedule to run weekly

chore(deps): reconfigure renovate

---

src/components/Link/Link.scss
src/components/Link/Link.tsx
stories/Link.tsx

Story: [ONEUI-202](https://jira.textkernel.nl/browse/ONEUI-202)

feat(Link): add context muted option

---

src/components/Chip/Chip.tsx
src/components/FieldWithValidation/FieldWithValidation.tsx
src/components/Heading/Heading.tsx
src/components/Heading/__tests__/__snapshots__/Heading.spec.js.snap
src/components/Icon/IconBase.tsx
src/components/Link/Link.tsx
src/components/Text/Text.tsx
stories/Tooltip.tsx

Story: [JF-1842](https://jira.textkernel.nl/browse/JF-1842) and [JF-1852](https://jira.textkernel.nl/browse/JF-1852)

Fix(Tooltip): allow most of our components to be wrapped in Tooltip

---

src/components/Autosuggest/Autosuggest.js
src/components/LocationAutocomplete/LocationAutocomplete.js
src/components/LocationAutocomplete/__tests__/__snapshots__/LocationAutocomplete.spec.js.snap
src/components/LocationSelector/LocationSelector.tsx
src/components/LocationSelector/LocationSelectorDialog/LocationSelectorDialog.js
src/components/LocationSelector/LocationSelectorDialog/__tests__/__snapshots__/LocationSelectorDialog.spec.js.snap
src/components/LocationSelector/LocationSelectorDialogWithGoogleLoader/LocationSelectorDialogWithGoogleLoader.js
src/components/LocationSelector/__tests__/__snapshots__/LocationSelector.spec.js.snap
stories/LocationAutocomplete.js

Story: [REACH-278](https://jira.textkernel.nl/browse/REACH-278)

feat(LocationAutocomplete): add an optional Clear button, update snapshots

---

src/components/Buttons/Button/Button.tsx
stories/Button.tsx

Story: [REACH-126](https://jira.textkernel.nl/browse/REACH-126)

fix(Button): add HTMLAnchorElement to Button props

---

PULL_REQUEST_TEMPLATE.md

Add Github pull request template for definition-of-done checklist in PRs

chore: add github pull request template

---

PULL_REQUEST_TEMPLATE.md

Fixes PR template formatting by adding list items.

chore: add list items to pr template

---

src/components/Select/SelectBase/SelectBase.tsx
stories/Select.tsx

fix(ComboboxMulti): fix dropdown expanding and minimising by clicking on the icon

---

src/components/SelectComponents/AutosuggestMulti/AutosuggestMulti.tsx
src/components/SelectComponents/AutosuggestMulti/__tests__/AutosuggestMulti.spec.js
src/components/SelectComponents/AutosuggestMulti/__tests__/__snapshots__/AutosuggestMulti.spec.js.snap
src/components/SelectComponents/SelectBase/index.ts
src/components/SelectComponents/SelectBase/interfaces.ts
stories/Select.tsx

Story: [JF-2387](https://jira.textkernel.nl/browse/JF-2387)

fix(AutosuggestMulti): only show noSuggestions if user already started to search

---

src/components/Drawer/Drawer.scss

refactor(drawer): made Drawer title more visible

---

src/components/SelectButtonGroup/SelectButton/SelectButton.scss
src/components/SelectButtonGroup/SelectButton/SelectButton.tsx
src/components/SelectButtonGroup/SelectButton/__tests__/__snapshots__/SelectButton.spec.js.snap
src/components/SelectButtonGroup/SelectButtonGroup/SelectButtonGroup.scss
src/components/SelectButtonGroup/SelectButtonGroup/SelectButtonGroup.tsx
src/components/SelectButtonGroup/SelectButtonGroup/__tests__/__snapshots__/SelectButtonGroup.spec.js.snap
stories/SelectButtonGroup.tsx

Restyles SelectButtonGroup components

feat(SelectButtonGroup): restyled component

---

src/components/BulkActionsToolbar/BulkActionsToolbar.scss

Enhanced paddings for BulkActionsToolbar
**Demo**: https://monosnap.com/file/smAjCn2bQlLJfoqeCPuykUd2FzLzQp

fix(BulkActionsToolbar): fix paddings for BulkActionsToolbar counter

---

src/components/Heading/Heading.scss

Fix(Heading): Remove static font color

---

src/components/Pagination/Pagination.tsx
src/components/Pagination/__tests__/Pagination.spec.js

fix(Pagination): fixed ability to set maxPageButtons=0

---

src/components/ProgressBar/ProgressBar.scss

fix(ProgressBar): remove fill minimum width

---

src/packages/BooleanQueryTokenizer/BooleanQueryTokenizer.ts
src/packages/BooleanQueryTokenizer/__tests__/BooleanQueryTokenizer.spec.js
stories/packages/BooleanQueryTokenizer.tsx

feat(BooleanQueryTokenizer): implement bag of words with excluded negations

---

src/components/SelectComponents/Autosuggest/Autosuggest.tsx
src/components/SelectComponents/Autosuggest/__tests__/Autosuggest.spec.js
src/components/SelectComponents/Autosuggest/__tests__/__snapshots__/Autosuggest.spec.js.snap
stories/Select.tsx

Fixed issue with loading expansions for related selected terms while input empty.
Task: https://jira.textkernel.nl/browse/ONEUI-234

fix(Autosuggest): fix showing suggestions on focus input

---

src/components/WeightedResultBar/WeightedResultBar.tsx
src/components/WeightedResultBar/__tests__/WeightedResultBar.spec.js
src/components/WeightedResultBar/__tests__/__snapshots__/WeightedResultBar.spec.js.snap
stories/WeightedResultBar.tsx

[ONEUI-239](https://jira.textkernel.nl/browse/ONEUI-239)

feat(WeightedResultBar): extend a component with a custom count

---

src/components/Heading/Heading.scss
src/components/Heading/Heading.tsx
src/components/Heading/__tests__/Heading.spec.js
src/components/Heading/__tests__/__snapshots__/Heading.spec.js.snap
stories/Heading.tsx

feat(Heading): add new context prop

---

src/components/Navigation/NavItem/NavItem.tsx
stories/List.tsx

feat(NavLink): extend the component with ref prop

---

src/components/Modal/Modal.tsx
src/components/Modal/index.ts
src/components/ProductTour/ProductTour.scss
src/components/ProductTour/ProductTour.tsx
src/components/ProductTour/__mocks__/slides.tsx
src/components/ProductTour/__tests__/ProductTour.spec.js
src/components/ProductTour/__tests__/__snapshots__/ProductTour.spec.js.snap
src/components/ProductTour/index.ts
src/index.ts
stories/ProductTour.tsx
stories/index.ts

feat(ProductTour): new component

---

src/components/Toggle/Toggle.scss
src/components/Toggle/Toggle.tsx
src/components/Toggle/__tests__/Toggle.spec.js
src/components/Toggle/__tests__/__snapshots__/Toggle.spec.js.snap
src/components/Toggle/index.ts
src/index.ts
stories/Toggle.js
stories/index.ts

Add a new Toggle component.
Related story: https://jira.textkernel.nl/browse/ONEUI-241

feat(Toggle): new component

---

src/components/Toggle/Toggle.scss

fix(Toggle): add styles for disabled checked state

---

package-lock.json

Resolves vulnerabilities reported by dependabot

chore(deps): fix dependabot alerts

---

renovate.json

[Story ONEUI-250](https://jira.textkernel.nl/browse/ONEUI-250)

chore(deps): update renovate config

---

src/components/Highlighter/ReactElementHighlighter/ReactElementHighlighter.tsx

feat(component): make onComplete optional in ReactElementHighlighter

---

src/components/BulkActionsToolbar/BulkActionsToolbar.scss
src/components/BulkActionsToolbar/BulkActionsToolbar.tsx
src/components/BulkActionsToolbar/__tests__/BulkActionsToolbar.spec.js
src/components/BulkActionsToolbar/__tests__/__snapshots__/BulkActionsToolbar.spec.js.snap
stories/BulkActionsToolbar.tsx

Relates to https://jira.textkernel.nl/browse/ONEUI-276

feat(BulkActionsToolbar): enable actions custom button context

---

src/components/Buttons/StepperButton/StepperButton.scss
src/components/Buttons/StepperButton/StepperButton.tsx
src/components/Buttons/StepperButton/__tests__/StepperButton.spec.js
src/components/Buttons/StepperButton/__tests__/__snapshots__/StepperButton.spec.js.snap
src/components/Buttons/StepperButton/index.ts
src/components/Buttons/index.ts
src/components/NumericStepper/NumericStepper.scss
src/components/NumericStepper/NumericStepper.tsx
src/components/NumericStepper/__tests__/NumericStepper.spec.js
src/components/NumericStepper/__tests__/__snapshots__/NumericStepper.spec.js.snap
src/components/NumericStepper/index.ts
src/index.ts
src/themes/oneui/base-variables/_sizing.scss
stories/Button.tsx
stories/NumericStepper.tsx
stories/index.ts

Add new NumericStepper component
Related story: [https://jira.textkernel.nl/browse/ONEUI-258](https://jira.textkernel.nl/browse/ONEUI-258)

feat(NumericStepper): add NumericStepper component

---

package-lock.json
package.json
src/components/Dialogs/Alert/__tests__/__snapshots__/Alert.spec.js.snap
src/components/Dialogs/Confirm/__tests__/__snapshots__/Confirm.spec.js.snap
src/components/LocationSelector/__tests__/__snapshots__/LocationSelector.spec.js.snap
src/components/LocationSelector/utils.ts
src/components/Modal/__tests__/__snapshots__/Modal.spec.js.snap
src/components/ProductTour/__tests__/__snapshots__/ProductTour.spec.js.snap

There are several commits that mysteriously made their way into our master branch. These renovate updates created failing pipelines. I reverted on (TS update) and fixed the others.

Fix master

---

src/components/NumericStepper/NumericStepper.tsx
src/components/NumericStepper/__tests__/NumericStepper.spec.js
src/components/NumericStepper/__tests__/__snapshots__/NumericStepper.spec.js.snap

fix(NumericStepper): update component state if props change

---

.circleci/config.yml
src/components/Gauge/Gauge.tsx
src/components/Gauge/__tests__/__snapshots__/Gauge.spec.js.snap

Story: [JF-2780](https://jira.textkernel.nl/browse/JF-2780)

fix(Gauge): improve HTML to ensure correct rendering in all browsers

---

README.md

Replaces dependency badge in README.md

docs: replace dependency status badge

---

src/components/Gauge/Gauge.scss
src/components/Gauge/Gauge.tsx
src/components/Gauge/__tests__/Gauge.spec.js
src/components/Gauge/__tests__/__snapshots__/Gauge.spec.js.snap
stories/Gauge.tsx

Story: [JF-2780](https://jira.textkernel.nl/browse/JF-2780)
See details in comments there

fix(Gauge): Safari bug where gradient doesn't render

---

package-lock.json
package.json

Revert "chore(deps): update dependency node-notifier to 8.0.1 [security]"

---

package-lock.json
package.json

Revert "chore(deps): update babel monorepo to v7.16.7"

---

package-lock.json
package.json

Revert "chore(deps): update dependency @types/node to v12.20.40"

---

src/components/Footer/__tests__/__snapshots__/Footer.spec.js.snap

fix: update footer snapshot

---

.github/workflows/check.yml

Trigger workflow on both push and pull request events.

ci: run checks on push and pull requests

---

src/components/BulkActionsToolbar/BulkActionsToolbar.scss
src/components/BulkActionsToolbar/BulkActionsToolbar.tsx
stories/BulkActionsToolbar.tsx

feat(component): update BulkActionsToolbar component

---

src/components/BulkActionsToolbar/BulkActionsToolbar.scss

style: refactor space and size

---

src/components/BulkActionsToolbar/BulkActionsToolbar.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/index.ts
src/index.ts
stories/BulkActionsToolbar.tsx

style: add delay to BulkActionsToolbar

---

src/components/FieldWrapper/FieldWrapper.scss
src/components/SelectComponents/Select/__tests__/__snapshots__/Select.spec.js.snap
src/components/SelectComponents/SelectBase/SelectBase.scss
src/components/SelectComponents/SelectBase/SelectBase.tsx

feat(component): improving clear button for selectBase

---

package-lock.json
package.json

fix: fix ts-jest version

---

src/components/Map/Map/Map.tsx

Story: [JF-3156](https://textkernel.atlassian.net/browse/JF-3156)

fix(Map): doesn't zoom on initial addition of marker

---

src/components/Themeroller/ThemeActions/ThemeActions.scss
src/components/Themeroller/ThemeActions/ThemeActions.tsx
src/components/Themeroller/ThemeActions/__tests__/__snapshots__/ThemeActions.spec.js.snap
src/components/Themeroller/Themeroller.tsx
src/components/Themeroller/__tests__/__snapshots__/Themeroller.spec.js.snap
stories/Themeroller.tsx

refactor: added back to default theme button

---

src/packages/Highlighter/HighlighterCore/HighlighterCore.ts
src/packages/Highlighter/HighlighterCore/__tests__/HighlighterCore.spec.js

fix: highlighter highlight terms with special characters correctly

---

src/components/LabelPicker/LabelPicker.scss

Story: [ONEUI-317](https://textkernel.atlassian.net/browse/ONEUI-317)

fix(LabelPicker): change spacing of elements

---

src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/__tests__/ButtonGroup.spec.js
src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.js.snap
stories/ButtonGroup.js

Story: [ONEUI-318](https://textkernel.atlassian.net/browse/ONEUI-318)

fix(ButtonGroup): styling when only has 1 child

---

src/components/Tag/Tag.tsx

Pass events to handlers in Tag

fix(Tag): pass event to handlers in Tag

---

src/themes/OneUITheme/baseVariables/colors.ts
src/themes/oneui/base-variables/_colors.scss

feat: add new color for shadow in background

---

src/components/Buttons/Button/Button.tsx
src/components/Icon/IconBase.tsx
src/components/List/ListItem/ListItem.tsx
src/components/TwoPaneView/LeftPane/LeftPane.tsx
src/components/WidthRestrictor/BlockWidthRestrictor/BlockWidthRestrictor.tsx

fix: forwardRef type errors

---

package-lock.json
package.json
src/components/Navigation/NavItem/NavItem.tsx
src/components/Navigation/NavItem/__tests__/NavItem.spec.js
src/components/Navigation/NavItem/__tests__/__snapshots__/NavItem.spec.js.snap
stories/molecules/Navigation.tsx

Story: [ONEUI-331](https://textkernel.atlassian.net/browse/ONEUI-331)

feat(NavItem): support react-router v6

---

src/components/Pill/Pill.tsx
src/components/Pill/PillDropdown/PillDropdown.tsx
src/components/Pill/PillDropdown/index.ts
src/components/Pill/index.ts
src/index.ts

fix(typescript): fixed Pill typescript props

---

src/components/Pill/Pill.tsx
src/components/Pill/PillButton/PillButton.tsx
src/components/PopupBase/PopupBase.tsx

fix: type content for pill and pillButton components

---

src/components/RadioButton/RadioButton.tsx

fix: children type for radio button component

---

package.json

chore: fix incorrect constraints in package.json

---

package-lock.json
package.json
src/components/Navigation/NavBar/NavBar.scss
src/components/Navigation/NavItem/NavItem.scss

feat: change top navigation bar

---

.husky/pre-commit
package-lock.json
package.json

chore: husky update from v4 to v8

---

package.json
src/components/DatePicker/CalendarHeader/CalendarHeader.scss
src/components/DatePicker/DatePicker.scss
src/themes/oneui/placeholders/_input.scss

feat: notification and activity report popup changes

---

package-lock.json
package.json
src/components/BulkActionsToolbar/BulkActionsToolbar.scss
src/components/Chip/Chip.scss
src/components/Drawer/Drawer.scss
src/components/FieldWrapper/FieldWrapper.scss
src/components/Input/Input.scss
src/components/Input/Input.tsx
src/components/List/ListItem/ListItem.scss
src/components/List/ListItem/ListItem.tsx
src/components/Pagination/PaginationButton/PaginationButton.scss
src/components/Pill/PillButton/PillButton.scss
src/components/Tabs/TabItem/TabItem.scss
src/components/Tabs/TabsBar/TabsBar.scss
src/components/Teaser/Teaser.scss
src/components/Text/Text.scss
src/components/Toggle/Toggle.scss

feat: search page changes according to new design

---

package-lock.json
package.json
src/components/PopupBase/PopupBase.tsx
src/components/PopupBase/index.ts

Reach 1190 fix popup base props

---

src/components/TextArea/TextArea.tsx
stories/atoms/TextArea.tsx

fix(textarea): set correct extend component for textarea

---

.github/workflows/measure-enzyme-to-rtl-tests-ratio.yml
package.json
scripts/measure-enzyme-to-rtl-tests-ratio/measure-enzyme-to-rtl-tests-ratio.js

feat: set up process to measure migration progress

---

.github/workflows/measure-enzyme-to-rtl-tests-ratio.yml

Update rtl migration script

---

.github/workflows/measure-enzyme-to-rtl-tests-ratio.yml
scripts/measure-enzyme-to-rtl-tests-ratio/measure-enzyme-to-rtl-tests-ratio.js

feat: update rtl script

---

src/components/Buttons/FileButton/FileButton.tsx
src/components/Themeroller/ThemeActions/ThemeActions.tsx
src/components/Themeroller/ThemeActions/__tests__/__snapshots__/ThemeActions.spec.js.snap
stories/atoms/Button.tsx

fix: remove context

---

src/components/Buttons/FileButton/FileButton.tsx
src/components/Pill/PillButton/PillButton.scss
src/components/Pill/PillButton/PillButton.tsx
src/components/Pill/PillButton/__tests__/__snapshots__/PillButton.spec.tsx.snap
src/components/Pill/__tests__/__snapshots__/Pill.spec.tsx.snap
src/components/Themeroller/ThemeActions/ThemeActions.tsx
src/components/Themeroller/ThemeActions/__tests__/__snapshots__/ThemeActions.spec.js.snap
src/themes/oneui/base-variables/_colors.scss
stories/atoms/Button.tsx

feat: Pill icon doesn't indicate open/closed state correctly

---

src/components/RadioButton/RadioButton.tsx

Story: https://textkernel.atlassian.net/browse/ONEUI-377

fix: RadioButton Props extends

---

TESTING_LIBRARY_MIGRATION.md
src/components/Buttons/Button/__tests__/Button.spec.tsx
src/components/Callout/__tests__/Callout.spec.js
src/components/Callout/__tests__/__snapshots__/Callout.spec.js.snap
src/components/CandidateAvatar/CandidateAvatar.tsx
src/components/CandidateAvatar/__tests__/CandidateAvatar.spec.js
src/components/CandidateAvatar/__tests__/__snapshots__/CandidateAvatar.spec.js.snap
src/components/ContentPlaceholder/ContentPlaceholder.tsx
src/components/ContentPlaceholder/__tests__/ContentPlaceholder.spec.js
src/components/ContentPlaceholder/__tests__/__snapshots__/ContentPlaceholder.spec.js.snap
src/components/SelectComponents/Autosuggest/__tests__/Autosuggest.spec.tsx
src/components/SelectComponents/Autosuggest/__tests__/__snapshots__/Autosuggest.spec.tsx.snap
src/components/SelectComponents/Combobox/__tests__/Combobox.spec.tsx
src/components/SelectComponents/ComboboxMulti/__tests__/ComboboxMulti.spec.tsx
src/components/SelectComponents/SuggestionsList/__tests__/__snapshots__/SuggestionsList.spec.js.snap

Story: [ONEUI-356](https://textkernel.atlassian.net/browse/ONEUI-356)

test: Callout, CandidateAvatar and ContentPlaceholder components tests migration

---

src/components/Buttons/Button/Button.tsx
src/components/Buttons/Button/__tests__/Button.spec.tsx
src/components/Buttons/FileButton/FileButton.tsx
src/components/Buttons/FileButton/__tests__/FileButton.spec.tsx
src/components/Callout/Callout.tsx
src/components/Callout/__tests__/Callout.spec.tsx
src/components/Chip/Chip.tsx
src/components/Chip/__tests__/Chip.spec.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Gauge/Gauge.tsx
src/components/Gauge/__tests__/Gauge.spec.js
src/components/Heading/Heading.tsx
src/components/Heading/__tests__/Heading.spec.tsx
src/components/Icon/IconBase.tsx
src/components/Icon/__tests__/IconBase.spec.tsx
src/components/Link/Link.tsx
src/components/Link/__tests__/Link.spec.js
src/components/SelectButtonGroup/SelectButton/SelectButton.tsx
src/components/SelectButtonGroup/SelectButton/__tests__/SelectButton.spec.js
src/components/SelectComponents/Autosuggest/SuggestionTag/SuggestionTag.tsx
src/components/SelectComponents/Autosuggest/SuggestionTag/__tests__/SuggestionTag.spec.js
src/components/SelectedOption/SelectedOption.tsx
src/components/SelectedOption/__tests__/SelectedOption.spec.js
src/components/Text/Text.tsx
src/components/Text/__tests__/Text.spec.tsx

Story: [JF-3938](https://textkernel.atlassian.net/browse/JF-3938)

fix: unintentional breaking changes where components don't render with children 0

---

src/components/SelectComponents/Select/Select.tsx
src/components/SelectComponents/Select/__tests__/Select.spec.js
src/components/SelectComponents/Select/__tests__/__snapshots__/Select.spec.js.snap
stories/organisms/Select.tsx

Story: [JF-3902](https://textkernel.atlassian.net/browse/JF-3902)

fix(Select): don't show Clear button if onClear isn't defined

---

src/components/SelectComponents/Autosuggest/__tests__/Autosuggest.spec.tsx
src/components/SelectComponents/Combobox/__tests__/Combobox.spec.tsx
src/components/SelectComponents/Combobox/__tests__/__snapshots__/Combobox.spec.tsx.snap
src/components/SelectComponents/SelectBase/__tests__/SelectBase.spec.tsx

Task [link](https://textkernel.atlassian.net/browse/ONEUI-376)

refactor: tests refactoring and addressed TODO, Ignore It

---

src/components/Checkbox/Checkbox.tsx

Story: [JF-3908](https://textkernel.atlassian.net/browse/JF-3908)

fix: checkbox forward ref

---

src/components/LocationSelector/LocationSelector.scss

Task [link](https://textkernel.atlassian.net/browse/ONEUI-422)

fix: LocationSelector component text color

---

src/components/Tooltip/__tests__/Tooltip.spec.tsx
src/components/Tooltip/__tests__/__snapshots__/Tooltip.spec.tsx.snap

Story: [ONEUI-425](https://textkernel.atlassian.net/browse/ONEUI-425)

tests: improve Tooltip tests

---

src/components/Pill/Pill.tsx
src/components/Pill/__tests__/Pill.spec.tsx
src/components/Pill/__tests__/__snapshots__/Pill.spec.tsx.snap

Story: [JF-4256](https://textkernel.atlassian.net/browse/JF-4256)

fix(Pill): extend Pill props to include all PillButton props

---

src/components/ButtonGroup/ButtonGroup.tsx
src/components/CandidateAvatar/CandidateAvatar.tsx
src/components/Drawer/Drawer.tsx
src/components/Dropdown/Dropdown.tsx
src/components/FieldWithValidation/FieldWithValidation.tsx
src/components/Gauge/Gauge.tsx
src/components/LocationAutocomplete/LocationAutocomplete.tsx
src/components/Pill/Pill.tsx
src/components/Pill/PillButton/PillButton.tsx
src/components/Pill/PillDropdown/PillDropdown.tsx
src/components/RadioButton/RadioButtonGroup.tsx
src/components/SelectComponents/Autosuggest/SuggestionTag/SuggestionTag.tsx
src/components/Themeroller/ThemeTuner/ThemeTuner.tsx

Tasl: [JF-4270](https://textkernel.atlassian.net/browse/JF-4270)

fix(TS): extend Prop interfaces where base element props were not included

---

scripts/build/webpack.config.js

Story: [JF-4277](https://textkernel.atlassian.net/browse/JF-4277)

fix(bundle): add empty publicPath to webpack config

---

src/components/LabelPicker/LabelPicker.tsx
src/components/LabelPicker/__tests__/LabelPicker.spec.tsx
stories/organisms/LabelPicker.stories.tsx

https://textkernel.atlassian.net/browse/ONEUI-433

fix(LabelPicker): delete 'done' button

---

src/components/LabelPicker/LabelPicker.tsx

[ONEUI-433](https://textkernel.atlassian.net/browse/ONEUI-433)

docs(LabelPicker): remove done button from docs

---

src/components/Table/Table/Table.scss
src/components/Table/Table/Table.tsx
src/components/Table/Table/index.ts
src/components/Table/TableBody/TableBody.tsx
src/components/Table/TableBody/index.ts
src/components/Table/TableCell/TableCell.scss
src/components/Table/TableCell/TableCell.tsx
src/components/Table/TableCell/index.ts
src/components/Table/TableHead/TableHead.tsx
src/components/Table/TableHead/index.ts
src/components/Table/TableHeaderCell/TableHeaderCell.scss
src/components/Table/TableHeaderCell/TableHeaderCell.tsx
src/components/Table/TableHeaderCell/index.ts
src/components/Table/TableRow/TableRow.scss
src/components/Table/TableRow/TableRow.tsx
src/components/Table/TableRow/index.ts
src/components/Table/__tests__/Table.spec.tsx
src/components/Table/__tests__/__snapshots__/Table.spec.tsx.snap
src/components/Table/index.ts
src/index.ts
stories/atoms/Table.stories.tsx

Story: [ONEUI-443](https://textkernel.atlassian.net/browse/ONEUI-443)

feat(Table): new opinionated component to render HTML semantic tables

---

.storybook/main.ts
package-lock.json
package.json
scripts/build/utils/utils.js
scripts/build/webpack.config.js
scripts/build/webpack.dev.config.js
scripts/build/webpack.prod.config.js
src/components/Buttons/Button/Button.scss
src/components/ExpandableText/ExpandableText.scss
src/components/ExpandableText/ExpandableText.tsx
src/components/ExpandableText/__tests__/ExpandableText.spec.tsx
src/components/ExpandableText/__tests__/__snapshots__/ExpandableText.spec.tsx.snap
src/components/ExpandableText/index.ts
src/index.ts
src/types/modules.d.ts
stories/molecules/ExpandableText.stories.tsx

Story:[ONEUI-442](https://textkernel.atlassian.net/browse/ONEUI-442)

feat(ExpandableText): new component

---

src/themes/OneUITheme/baseVariables/sizing.ts
src/themes/OneUITheme/baseVariables/typography.ts
src/themes/oneui/base-variables/_colors.scss
src/themes/oneui/base-variables/_header_footer.scss
src/themes/oneui/base-variables/_misc.scss
src/themes/oneui/base-variables/_sizing.scss
src/themes/oneui/base-variables/_typography.scss
src/themes/themerollerConfig/themerollerConfig.ts

Story: [ONEUI-466](https://textkernel.atlassian.net/browse/ONEUI-466)
BREAKING CHANGE: some unused CSS variables removed: --line-medium, --line-thick, --outline-size

chore(css variables): define them directly not via SCSS

---

src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/__tests__/__snapshots__/Checkbox.spec.tsx.snap
src/themes/oneui/base-variables/_sizing.scss
stories/molecules/Checkbox.stories.tsx

Story: [ONEUI-444](https://textkernel.atlassian.net/browse/ONEUI-444)

feat(Checkbox): migrate to new design

---

src/components/RadioButton/RadioButton.scss
src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/__tests__/__snapshots__/RadioButton.spec.tsx.snap
src/components/RadioButton/__tests__/__snapshots__/RadioButtonGroup.spec.tsx.snap
src/constants/style-related.ts

Story: [ONEUI-445](https://textkernel.atlassian.net/browse/ONEUI-445)

feat(RadioButton): migrate to new design

---

src/components/Toggle/Toggle.scss
src/components/Toggle/Toggle.tsx

Story: [ONEUI-449](https://textkernel.atlassian.net/browse/ONEUI-449)

feat(Toggle): migrate to new design

---

RELEASING.md

[ONEUI - 490](https://textkernel.atlassian.net/browse/ONEUI-490)

docs: update release documentation

---

src/components/Buttons/Button/Button.scss
src/components/Buttons/IconButton/IconButton.scss
src/components/Buttons/IconButton/IconButton.tsx
src/components/Buttons/IconButton/__tests__/IconButton.spec.tsx
src/components/Buttons/IconButton/__tests__/__snapshots__/IconButton.spec.tsx.snap
src/components/Buttons/IconButton/index.ts
src/components/Buttons/index.ts
src/themes/OneUITheme/baseVariables/sizing.ts
src/themes/oneui/base-variables/_sizing.scss
stories/atoms/Button.stories.tsx

Story: [ONEUI-473](https://textkernel.atlassian.net/browse/ONEUI-473)

feat(IconButton): new component

---

src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/__tests__/__snapshots__/Tooltip.spec.tsx.snap
stories/molecules/Tooltip.stories.tsx

[ONEUI-491](https://textkernel.atlassian.net/jira/software/c/projects/ONEUI/boards/119?assignee=712020%3A63f9d6c8-c4f1-488d-8002-8599ae3602af&assignee=unassigned&selectedIssue=ONEUI-491)
…d make sure that the font of the tooltip is 14px

feat(Tooltip): updated the tooltip to the new design

---

src/components/DatePicker/DatePicker.scss

[ONEUI-499](https://textkernel.atlassian.net/browse/ONEUI-499)

style(DatePicker): remove boxshadow

---

src/components/Toaster/Toaster.tsx

[ONEUI-511](https://textkernel.atlassian.net/browse/ONEUI-511)

fix(Toast): remove empty space when there is no title

---

src/components/Dropdown/Items/MultiSelectItem/MultiSelectItem.tsx
src/components/Dropdown/Items/SingleSelectItem/SingleSelectItem.tsx
src/components/PrioritySelector/PrioritySelector.scss
src/components/PrioritySelector/PrioritySelector.tsx
src/components/PrioritySelector/__tests__/PrioritySelector.spec.tsx
src/components/PrioritySelector/__tests__/__snapshots__/PrioritySelector.spec.tsx.snap
src/components/PrioritySelector/index.ts
src/components/SelectedItemBadge/SelectedItemBadge.tsx
src/components/SelectedItemBadge/index.ts
src/index.ts
src/utils/misc.ts
stories/atoms/Dropdown.stories.tsx
stories/atoms/MultiSelectItem.stories.tsx
stories/atoms/SingleSelectItem.stories.tsx
stories/molecules/PrioritySelector.stories.tsx
stories/organisms/SelectedItemBadge.stories.tsx

[ONEUI-489](https://textkernel.atlassian.net/browse/ONEUI-489)
-   [ ] The Pull Request title follows our guidelines eg. `feat(PrioritySelector): new component`
-   [ ] Breaking changes are mentioned eg. `BREAKING CHANGE: isMultiSelect prop is removed`, if any.
-   [ ] Squash and Merge option is selected as merge option.

feat(PrioritySelector): new component

---

src/components/Tabs/TabItem/TabItem.scss
src/components/Tabs/TabsBar/TabsBar.scss

[ONEUI-512](https://textkernel.atlassian.net/browse/ONEUI-512)

fix(TabsBar): border full width and jumping

---

src/components/Dropdown/Dropdown.scss
src/components/Pill/Pill.tsx
src/components/Pill/PillButton/PillButton.scss
src/components/Pill/PillButton/PillButton.tsx
src/components/Pill/PillButton/__tests__/PillButton.spec.tsx
src/components/Pill/PillButton/__tests__/__snapshots__/PillButton.spec.tsx.snap
src/components/Pill/PillButtonEnhanced/PillButtonEnhanced.scss
src/components/Pill/PillButtonEnhanced/PillButtonEnhanced.tsx
src/components/Pill/PillButtonEnhanced/__tests__/PillButtonEnhanced.spec.tsx
src/components/Pill/PillButtonEnhanced/__tests__/__snapshots__/PillButtonEnhanced.spec.tsx.snap
src/components/Pill/PillDropdown/PillDropdown.scss
src/components/Pill/__tests__/Pill.spec.tsx
src/components/Pill/__tests__/__snapshots__/Pill.spec.tsx.snap
src/components/PrioritySelector/PrioritySelector.scss
src/utils/index.ts
stories/molecules/Pill.stories.tsx

BREAKING CHANGE: PillButton props `toggleDropdown` removed
BREAKING CHANGE: Pill uses RadixDropdown under the hood.
[ONEUI-514](https://textkernel.atlassian.net/browse/ONEUI-514)

fix(Pill): bugs in Pill with Enhanced options

---

CHANGELOG.md

[ONEUI-517](https://textkernel.atlassian.net/browse/ONEUI-517)
-   [X] The Pull Request title follows our guidelines eg. `feat(PrioritySelector): new component`
-   [X] Breaking changes are mentioned eg. `BREAKING CHANGE: isMultiSelect prop is removed`, if any.
-   [X] Squash and Merge option is selected as merge option.

fix: add teaser breaking change to changelog version 27.0.0

---

src/components/Breadcrumb/Breadcrumb.scss
src/components/Breadcrumb/Breadcrumb.tsx
src/components/Breadcrumb/__tests__/Breadcrumb.spec.tsx
src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb.spec.tsx.snap
src/components/Breadcrumb/index.ts
src/constants/component-specific.ts
src/index.ts
stories/atoms/Breadcrumb.stories.tsx

[ONEUI-504](https://textkernel.atlassian.net/browse/ONEUI-504)

feat(Breadcrumb): new component

---

CHANGELOG.md

fix(Changelog): add breaking changes

---

src/components/Checkbox/VisualCheckbox/VisualCheckbox.scss
src/components/Dropdown/DropdownContent/DropdownContent.tsx
src/components/SelectedItemBadge/SelectedItemBadge.scss
src/components/SelectedItemBadge/SelectedItemBadge.tsx

[ONEUI-522](https://textkernel.atlassian.net/browse/ONEUI-522)

fix(SelectedItemBadge): width and scrolling of the dropdown
